themost-framework/data

- data-cache.js
The data-cache module uses the `getOrDefault` function to call a user defined function on cache miss.
This PR adds a `catch` statement at the `getOrDefault` to catch errors on the user defined function.
> Handle promise rejection at getOrDefault of data-cache

- data-queryable.d.ts
This corrects the function declarations of `greaterOrEqual` and adds `in` and `notIn`. This would help intellisense suggest the correct function and not complain about the other functions
> Add function definitions

- data-configuration.js
- data-context.d.ts
- data-model.d.ts
- data-model.js
- package-lock.json
- package.json
- spec/DataModel.spec.ts
- spec/DataNestedObjectListener.spec.ts
- spec/DataObjectAssociationListener.spec.ts
- spec/helpers/env.js
- spec/test1/config/models/OtherProduct.json
- spec/test2/config/models/Product.json
- spec/test2/config/models/ProductDimension.json
- spec/test2/config/models/SpecialOffer.json
This PR adds `DataModel.migrateAsync()` method for upgrading data models within `async/await` procedures e.g. `await model.migrateAsyc()`
> Add migrate async

- data-model.d.ts
- data-model.js
- package-lock.json
- package.json
- spec/DataModel.upsert.spec.ts
- spec/test2/config/models/AccessLevelType.json
This PR closes #71 by adding DataModel.upsert() method which validates the existence of an object before inserting or updating it.
> add DataModel.upsert() method

- data-field-query-resolver.js
- data-listeners.js
- model-schema.json
- spec/CustomQueryExpr.spec.ts
- spec/TestApplication.ts
- types.d.ts
This MR adds a new feature for defining custom query expressions for readonly fields. This operation allows parsing custom query expressions and include them in data model's view adapter.
e.g. A business process needs customer's email address `customer.email` to be an attribute of an `Order` even if it would be retrieved by expanding `customer`.
Define a readonly attribute `orderEmail`
```
{
"name": "orderEmail",
"readonly": true,
"type": "Text",
"nullable": true,
"query": [
{
"$lookup": {
"from": "Person",
"foreignField": "id",
"localField": "customer",
"as": "customer"
}
},
{
"$project": {
"orderEmail": "$customer.email"
}
}
]
}
```
where `orderEmail` has a custom query with two stages:
1. Join `Person` collection based on `customer` attribute of an order.
```
{
"$lookup": {
"from": …
```
> Custom query expression

- data-model.js
- model-schema.json
- package-lock.json
- package.json
- spec/CustomQueryExpr.spec.ts
- types.d.ts
This MR closes #94 and implements `DataField.insertable` for handling virtual columns that should be included only in view data objects.
e.g.
```
{
"name": "ExtendedProduct",
"version": "3.0.0",
"inherits": "Product",
"fields": [
{
"name": "priceCategory",
"type": "Text",
"readonly": true,
"insertable": false,
"editable": false,
"nullable": true,
"query": [
{
"$project": {
"priceCategory": {
"$cond": [
{
"$gt": [
"$price",
1000
]
},
'Expensive',
'Normal'
]
}
}
}
]
}
],
"privileges": [
{
"mask": 15,
"type": "global"
},
{
"mask": 15,
"type": "global",
"account": "Administrators"
},
{
"mask": 1,
"type": "self",
"filter": "customer/user eq me()"
}
]
}
```
> Use insertable attribute

- data-model-filter.parser.d.ts
- data-model-filter.parser.js
- data-model.d.ts
- data-model.js
- data-permission.d.ts
- data-permission.js
- model-schema.json
- package-lock.json
- package.json
- spec/DataPrivilege.exclude.spec.ts
- types.d.ts
This PR closes #96 by implementing `DataModelPrivilege.scope` which may be used to exclude privileges defined for specific client scopes. The meaning of "scope" is included in OAuth2 authorised environments but it can be used by any environment which implements such protocols. 
e.g. `Order` model defines a self privilege for giving access to customers for reading their orders. This privilege may be validated only when context includes `orders` or `orders:readonly` scopes.
```
{
"mask": 1,
"type": "self",
"filter": "customer/user eq me()"
"scope": [
"orders",
"orders:readonly"
]        
}
```
> create data filter parser

- odata.d.ts
- odata.js
- package-lock.json
- package.json
- spec/ODataModelBuilder.spec.ts
- spec/test2/config/models/Thing.json
- spec/test2/config/models/User.json
- spec/test2/config/models/UserChat.json
- spec/test2/config/models/UserComment.json
- spec/test2/config/models/UserReview.json
- spec/test2/models/Account.ts
- spec/test2/models/Thing.ts
- spec/test2/models/User.ts
- types.d.ts
This PR validates entity types collection when entity set is being ignored -DataMode.hidden equals to true- but the entity type is used by other entity types in properties, navigation properties, functions or actions.
e.g. `UserReview` is a hidden model
```
{
"$schema": "https://themost-framework.github.io/themost/models/2018/2/schema.json",
"name": "UserReview",
"title": "UserReviews",
"hidden": true,
"sealed": false,
"abstract": false,
"version": "1.0",
"inherits": "Review",
"fields": [
{
"name": "user",
"type": "User",
"nullable": false
}
]
}
```
but is being used as parameter of an action of `User` model.
```
@EdmMapping.param('userReview', 'UserReview', false, true)
@EdmMapping.action('Review', 'Object')
async review(userReview: any) {
await …
```
> Validate visible entity types

- odata.js
- package-lock.json
- package.json
- spec/ODataModelBuilder.spec.ts
This PR tries to include all properties and navigation properties that are being implemented by a data model while publishing OData service metadata document. 
It also removes any validation for ignoring entity types. This operation of ignoring an entity type defined is completely obsolete and should be removed because it may confuse OData clients while reading service metadata.
> Include implemented properties while publishing OData service metadata

- data-model.js
- package-lock.json
- package.json
- spec/DataModel.filter.spec.ts
This PR validates `$top` and `$skip` while passing those parameters as an argument of `DataModel.filter(queryOptions)` method and parses the given values as integers.
> validate $top and $skip params

- data-associations.js
- package-lock.json
- package.json
- spec/DataAttributeResolver.spec.ts
- spec/FunctionContext.spec.ts
- spec/test2/config/models/SubscribeAction.json
- spec/test2/config/models/Thing.json
This MR closes #103 and validates if a given value which defines an associated object represents an empty object e.g. an object  id=0 where `id` is an auto increment identifier etc.
> if value is an empty object set associated object to null

- data-model.d.ts
- data-model.js
- package-lock.json
- package.json
This PR adds `DataModel.inferStateAsync(object)` method which is a promise-like alternative of `DataModel.inferState(object,callback)`.
> add DataModel.inferStateAsync

- data-model.d.ts
- data-model.js
- data-queryable.js
- package-lock.json
- package.json
- spec/DataModel.filter.spec.ts
- types.d.ts
This PR fixes a compatibility issue occurred while selecting a data view defined in a data model. This issue refers to `DataModel.filter()` method which uses `OpenDataParser` instead of internal select methods which were being used in previous versions.
> select data view

- data-model.js
- package-lock.json
- package.json
- spec/DataAssociationMapping.spec.ts
- spec/ParentChildRelationship.spec.ts
This PR fixes a backward compatibility issue of selecting attributes which define an many-to-many or one-to-many associations. These attributes should be include in `$expand` system query option but sometimes are being used as part of `$select` option.
> fix selection of expandable attributes

- data-model.js
- package-lock.json
- package.json
- spec/DataModel.filter.spec.ts
This PR validates expand expressions before adding join expressions extracted by system query options.  This operation is very important when selecting a data model view where attributes may contain join expressions.
> validate already defined expand expressions

- data-ref-object-listener.js
- package-lock.json
- package.json
- spec/DataObjectTag.spec.ts
This PR checks if `mapping.childModel` is null and uses `DataObjectTag` class instead of `HasParentJunction`. This operation is being used while trying to remove an object and its associated values.
> Use data object tag if child model is null

- data-model.d.ts
- data-model.js
- package-lock.json
- package.json
- spec/DataModel.spec.ts
This PR adds `DataModel.load` global event emitter for handling post loading process.
e.g. the following example uses `DataModel.load` event to force data caching for any model:
```javascript
// force caching for any model
DataModel.load.subscribe((event) => {
event.target.caching = 'always';
});
let model = context.model('Product');
```
> add load event

- OnNestedQueryOptionsListener.js
- data-model.js
- package-lock.json
- package.json
- spec/ZeroOneMultiplicity.spec.ts
- spec/test2/config/models/Product.json
- spec/test2/config/models/ProductDescription.json
This PR adds a new before execute listener for handling associations where a filter statement defines the condition representing an association between two entities. 
Let's assume that a product has a product description in different languages. `Product` model has also a virtual property `Product.productDescription` which defines the description of a product in current locale.
The collection of product descriptions:
```json
{
"name": "productDescriptions",
"type": "ProductDescription",
"nested": true,
"mapping": {
"parentModel": "Product",
"parentField": "id",
"childModel": "ProductDescription",
"childField": "product",
"associationType": "association",
"cascade": "delete"
}
}
``` 
The definition of the `productDescription` property:
```json
{
"name": "productDescription",
"type": …
```
> handle association object mapping with filter

- data-attribute-resolver.d.ts
- data-attribute-resolver.js
- data-model-filter.parser.d.ts
- data-model-filter.parser.js
- data-permission.d.ts
- data-permission.js
- package-lock.json
- package.json
- spec/DataPrivilege.exclude.spec.ts
- spec/test2/config/models/AnotherStructuredValue.json
- types.d.ts
This PR implements the exclusion of one or more privileges according to authentication scopes included in user context e.g. A customer should add an order when they have `orders` scope. This operation is being represented by a privilege like the following:
```json
{
"type": "self",
"mask": 14,
"filter": "customer/user eq me() and orderStatus/alternateName eq 'OrderProcessing'",
"scope": [
"orders"
]
}
```
where a customer is able to create, update or delete their own order with status equal to `OrderProcessing` when they have `orders` scope.
> excluding privileges according to authentication scopes

- OnNestedQueryOptionsListener.js
- package-lock.json
- package.json
This PR updates nested query mechanism and generates query expressions if this operation is required by an attribute e.g. an zero-or-one multiplicity association has a `$filter` which should be applied while getting nested attributes.
> reset nested query expression

- data-queryable.js
- package-lock.json
- package.json
Fixes an error occurred while selecting an attribute from a many-to-many association with zero or one multiplicity.
> set model name for a zero-or-one junction

- data-queryable.js
- spec/DataQueryable.spec.ts
This PR closes #161 and validates the existing where statement of an instance of `DataQueryable` when using `DataQueryable.where(expr)` and throws an error if has been already defined e.g. a DataQueryable instance is being used for getting a list of orders and the process is trying to add an extra clause by using again `where(expr)`. This statement will throw an exception: "The where expression has already been initialized.".
```js
const q = Orders.where('orderStatus/alternateName').equal('OrderDelivered')
.orderByDescending('orderDate').take(10);
q.where('orderedItem/category').equal('Laptops');
```
> Validate where statement

- data-field-query-resolver.js
- data-listeners.js
- data-model.js
- model-schema.json
- package-lock.json
- package.json
- spec/CustomQueryExpr.spec.ts
- types.d.ts
This PR implements a feature that has been already supported by `@themost/query@latest` as already has been described by https://github.com/themost-framework/data/pull/87 where an attribute may have a custom query expression before creating the database view object which represents the target model.
e.g. A business process needs customer's email address `customer.email` to be an attribute of an `Order` even if it would be retrieved by expanding `customer`.
Define a readonly attribute `orderEmail`
```
{
"name": "orderEmail",
"readonly": true,
"type": "Text",
"nullable": true,
"query": [
{
"$lookup": {
"from": "Person",
"foreignField": "id",
"localField": "customer",
"as": "customer"
}
},
{
"$project": {
"orderEmail": "$customer.email"
}
}
]
}
```
where `orderEmail` has a custom query with …
> implement custom query expression for attributes

- .github/workflows/test.yml
- data-configuration.d.ts
- data-configuration.js
- data-context.js
- package-lock.json
- package.json
- spec/DataApplication.spec.ts
- spec/DataConfiguration.spec.ts
- spec/TestApplication.ts
This PR changes `DataConfigurationStrategy.adapterTypes` type definition to be a `Map<string,DataAdapterType>`. This operation is useful for defining adapter types at runtime instead of using an application configuration file e.g.
```javascript
const app = new DataApplication(process.cwd());
const configuration = app.configuration.getStrategy(DataConfigurationStrategy);
// add sqlite adapter type
configuration.adapterTypes.set('sqlite', {
name: 'sqlite',
type: SqliteAdapter
});
// add test adapter type
configuration.adapters.push({
default: true,
invariantName: 'sqlite',
name: 'development',
options: {
database: ':memory:'
}
});
```
> set adapter types as map

- UnattendedMode.d.ts
- UnattendedMode.js
- index.d.ts
- index.js
- jest.config.js
- package-lock.json
- package.json
- spec/UnattendedMode.spec.ts
- tsconfig.json
This PR enables execution in unattended mode -a feature which has been already implemented by `@themost/data@latest`-
```javascript
await executeInUnattendedModeAsync(context, async () => {
const items = await context.model('Order').where('orderedItem/name').equal(
'Razer Blade (2013)'
).getItems();
});
```
> enable execution in attended mode

- data-model.js
- package-lock.json
- package.json
This pull request updates `DataModel.context` property to forcibly unregister existing listeners before setting value.
> Unregister context listeners before set

- data-model.js
- package-lock.json
- package.json
This pull requests update `DataMode.context` property and forcibly unregisters listeners before setting context.
> unregister listeners before setting context

- data-cache.d.ts
- data-cache.js
- package-lock.json
- package.json
- spec/DataCacheStrategy.spec.ts
This PR bumps node-cache to 5.1.2 and migrates `DataCacheStrategy` to use the new version of `NodeCache`.
> bump node-cache to 5.1.2

- OnJsonAttribute.js
- data-attribute-resolver.js
- data-model-filter.parser.js
- data-model.js
- data-pluralize.d.ts
- data-pluralize.js
- data-queryable.js
- data-value-resolver.js
- dataTypes.json
- jest.setup.js
- model-schema.json
- package-lock.json
- package.json
- spec/JsonAttribute.spec.ts
- spec/test2/config/models/Audience.json
- spec/test2/config/models/Product.json
- spec/test2/config/models/ProductMetadata.json
This PR implements the usage of JSON attributes -a feature which has been already implemented at LTS version- in a data model's schema e.g.
```json
{
"name": "metadata",
"many": false,
"type": "Json",
"additionalType": "ProductMetadata"
}
```
where `additionalType` attribute describes the schema of generic `Json` attribute:
```json
{
"$schema": "https://themost-framework.github.io/themost/models/2018/2/schema.json",
"title": "Product Metadata",
"name": "ProductMetadata",
"abstract": true,
"version": "1.0.0",
"fields": [
{
"name": "color",
"title": "Color",
"description": "A color related to the product.",
"type": "Text"
},
{
"name": "mpn",
"title": "Manufacturer Part Number",
"description": "The manufacturer part number (MPN) of the product.",
"type": "Text"
},
{
"name": "slogan", …
```
> use json attributes

- data-model.js
- package-lock.json
- package.json
- spec/DataModel.spec.ts
This PR updates `DataModel.clone()` method for properly cloning an instance of `DataModel` class.
> fix DataModel.clone()

- OnJsonAttribute.js
- data-model.js
- spec/JsonAttribute.spec.ts
- spec/test2/config/models/Product.json
This PR updates JSON attributes implementation for accepting data without validating them against a known object type e.g. `Product` model has a field `extraAttributes` where `additionalType` is missing which indicates that this field can accept any JSON value instead of validating it against a known object schema.
```json
{
"name": "extraAttributes",
"many": false,
"type": "Json"
}
```
where an update operation will omit validation of `extraAttributes` value.
```javascript
const item = await Products.where('name').equal('Apple MacBook Air (13.3-inch, 2013 Version)').getItem()
item.extraAttributes = {
cpu: 'Intel Core i5',
ram: '8GB'
}
await Products.save(item);
```
> use uknown json attribute

- data-cache.js
- package-lock.json
- package.json
This PR downgrades node-cache to version 1.1.0 for resolving performance issues
> downgrade node-cache back to 1.1.0

- data-mapping-extensions.js
- package-lock.json
- package.json
This PR updates `DataMappingExtender` to validate the given values that are going to be passed for getting associated objects and flatten them if they objects e.g. `{  "id": 450, "name": "A product"  }` instead of `450`.
> get values when passing objects

- data-mapping-extensions.js
- data-queryable.js
- package-lock.json
- package.json
This PR fixes and upgrades errors thrown by `DataMappingExtender` class when an association between two models is of a wrong type.
> Fix data mapping extender errors

- data-object-tag.js
- package-lock.json
- package.json
This PR changes the definition of data models automatically generated for `DataObjectTag` relationships to use the type of the parent object instead of the type of the primary key of the parent object. Data object tags define an association between a model and a collection of primitive typed values like Text, Number etc.
> set object type for data object tags

- data-application.d.ts
- data-application.js
- data-configuration.d.ts
- data-configuration.js
- package-lock.json
- package.json
- spec/DataApplication.spec.ts
This PR converts data configuration classes to ES6 classes following changes implemented at `@themost/common@2.12.0` for `ConfigurationBase` parent class.
> Convert configuration to es6 classes

- OnJsonAttribute.js
- data-attribute-resolver.js
- data-listeners.js
- data-state-validator.js
- jest.setup.js
- package-lock.json
- package.json
- spec/DataObjectTag.spec.ts
- spec/TestApplication.ts
- spec/adapter/TestUtils.ts
- spec/test2/config/models/Audience.json
- spec/test2/config/models/LanguageTypedString.json
- spec/test2/config/models/PeopleAudience.json
This PR updates object tags -a collection of primitive typed values associated with an object- to support JSON type values. This feature integrates data object tagging specification and allows the usage of complex types alongside with primitive types.
The following example
```json
{
"name": "preferredName",
"title": "Preferred Name",
"type": "Json",
"description": "The name preferred by the audience.",
"many": true,
"additionalType": "LanguageTypedString",
"mapping": {
"associationType": "junction",
"associationObjectField": "audience",
"associationValueField": "languageString"
}
}
```
describes `preferredName` field which uses a JSON object of type `LanguageTypedString`. This model might be defined using the following schema:
```json
{
"$schema": …
```
> use json fields as object tags

- data-model.js
- data-validator.d.ts
- data-validator.js
- package-lock.json
- package.json
This PR upgrades item validation to include json type attributes that have an additional type defined. This operation validates JSON objects against rules defined by the additional model e.g. a required value or a pattern validation etc. It also validates that the target object does not contain attributes that don't exist in target model.
> [LTS] Validate json type attributes
