themost-framework/data

odata.js
package-lock.json
package.json

add computed annotation to readonly attributes

---

odata.js
package-lock.json
package.json

add implements annotation

---

data-permission.d.ts
data-permission.js
package-lock.json
package.json
types.d.ts
types.js

Validate execute permissions

---

data-permission.js
package-lock.json
package.json

combine expand while validating permissions

---

odata.js

Closes #20  and validates schema loaders while initializing ODataConventionModelBuilder.

validate usage of schema loaders

---

odata.js
package-lock.json
package.json

This MR clears `ODataModelBuilder` cache during cleanup operation.

Manually clean builder

---

.vscode/launch.json
data-configuration.js
module-loader.d.ts
module-loader.js
spec/DataConfiguration.spec.ts
spec/test1/models/Account.ts
spec/test1/models/AccountModel.ts
types.d.ts
types.js

Load class module with hash

---

data-listeners.js
data-model.js
data-object.js
data-queryable.js
data-validator.js
functions.js
odata.js
package-lock.json
package.json

This MR closes #55 by replacing sprintf

Replace sprintf with sprint-js

---

data-model.js
data-nested-object-listener.js
data-object-junction.js
data-object.js
data-state-validator.js
data-validator.js
functions.js
has-one-association.js
has-parent-junction.js
package-lock.json
package.json

This MR removes the  call of built-in method `Object.prototype.hasOwnProperty` by replacing it with the util method provided by `./hasOwnProperty` module.

Remove built-in method call

---

OnExecuteNestedQueryable.js
OnNestedQueryListener.js
package-lock.json
package.json

This MR replace `Promise.all` calls with `Promise.sequence` provided by [@themost/promise-sequence](https://github.com/themost-framework/promise-sequence)

replace Promise.all with Promise.sequence

---

data-nested-object-listener.js
package-lock.json
package.json

This PR closes #65 by expanding a nested object property even if it has not been defined as `expandable`.

Ensure that nested object will be expanded

---

package-lock.json
package.json
spec/ZeroOneMultiplicy.spec.ts
spec/test2/config/models/Country.json
spec/test2/config/models/Product.json
zero-or-one-multiplicity.js

This PR sets `DataAssociationMapping.refersTo` while validating zero-or-one multiplicity association.

Force set DataAssociationMapping.refersTo attribute

---

data-object-junction.d.ts
data-object-junction.js
data-object-tag.d.ts
data-object-tag.js
data-object.d.ts
has-many-association.js
has-one-association.js
has-parent-junction.d.ts
has-parent-junction.js
jest.config.js
jest.setup.js
package-lock.json
package.json
spec/DataObjectJunction.spec.ts
spec/DataObjectTag.spec.ts
spec/HasParentJunction.spec.ts
spec/adapter/TestAdapter.ts
spec/test2/config/models/User.json
types.d.ts

This PR updates `DataObjectJunction` class to improve validation process of associated objects before updating or inserting items.

Validate associated object while inserting or removing items

---

data-associations.js
data-object-junction.d.ts
data-object-tag.d.ts
data-object-tag.js
data-queryable.d.ts
data-queryable.js
has-many-association.d.ts
has-parent-junction.d.ts
types.d.ts

This PR update DataQueryable type declaration and inserts the undocumented `DataQueryable.isSilent()` method which returns true or false to indicate whether an instance of DataQueryable class is acting in silent mode or not.

update DataQueryable type declaration

---

.codacy.yml
.npmignore
data-expand-resolver.js
data-filter-resolver.js
data-mapping-extensions.js
data-model.js
data-nested-object-listener.js
data-object-junction.js
data-permission.js
data-queryable.js
data-ref-object-listener.js
data-validator.d.ts
data-validator.js
functions.js
has-parent-junction.js
odata.js
spec/FunctionContext.spec.ts
types.js

This PR fixes some lint warnings and errors

Fix some lint warnings

---

data-object-junction.js
has-parent-junction.js
package-lock.json
package.json
spec/DataObjectJunction.spec.ts
spec/HasParentJunction.spec.ts

This MR forces the validation of a many-to-many association between two objects and throws an exception when is missing.

Validate association before remove

---

.github/workflows/npm-publish-next.yml
.github/workflows/npmpublish.yml
.github/workflows/test.yml
data-context.d.ts
data-context.js
package-lock.json
package.json
types.d.ts

This PR enables the usage of `@themost/common#DataAdapterBase` in type declarations.

use DataAdapterBase

---

data-mapping-extensions.js
package-lock.json
package.json

This PR validates the existence of key field while expanding nested many-to-many entities.

validate key field

---

data-mapping-extensions.js
data-queryable.js
jest.config.js
package-lock.json
package.json
spec/ParentChildRelationship.spec.ts

This PR closes #118 by filtering null values while returning parent objects of a parent-child association.

Filter null values

---

data-model.js
package-lock.json
package.json

This PR reset `configurable` property of `DataModel.attibutes`

set configurable properties

---

data-model.js
data-permission.js
package-lock.json
package.json

This PR closes #137 by simplifying the validation of `DataField.property` attribute.

Validate property attribute

---

data-object-junction.js
has-parent-junction.js
package-lock.json
package.json

This PR fixes the definition of an associated object of a many-to-many association when the given value is a single identifier.

define associated object

---

data-queryable.js
package-lock.json
package.json

This PR bump @themost/query to 2.13.1

bump @themost/query to 2.13.1

---

OnNestedQueryOptionsListener.js
data-model.d.ts
data-model.js
package-lock.json
package.json
spec/ZeroOneMultiplicy.spec.ts
spec/test2/config/models/Product.json
spec/test2/config/models/ProductDescription.json

This PR implements #150 to `@themost/data@lts`

handle data association with filter

---

data-attribute-resolver.d.ts
data-attribute-resolver.js
data-filter-resolver.js
data-model.js
data-queryable.js
package-lock.json
package.json

This PR upgrades data attribute resolver for handling json objects.

resolve json object attribute

---

data-attribute-resolver.js
data-errors.d.ts
data-errors.js
data-filter-resolver.js
data-queryable.js
index.d.ts
index.js
most-data-resources.en-us.json
package-lock.json
package.json
spec/DataQueryable.spec.ts

This PR validates attribute names used by expressions even if they refer to a nested attribute.

Validate attribute on filter or select

---

data-queryable.js
package-lock.json
package.json

This PR checks also query.$prepared when validating where statement

Validate where/or/and statement by checking also $prepared

---

package-lock.json
package.json
select-object-query.js

Check mapping existence on select query

Ignore property if model association is not defined

---

.codacy.yml
UnattendedMode.d.ts
UnattendedMode.js
index.d.ts
index.js
jest.config.js
jest.setup.js
package-lock.json
package.json
spec/DataModel.upsert.spec.ts
spec/TestApplication.ts
spec/UnattendedMode.spec.ts
tsconfig.json

This PR closes #171 and implements unattended execution helper function

implement unattended helper functions

---

data-attribute-resolver.js
data-queryable.js
data-value-resolver.d.ts
data-value-resolver.js
index.d.ts
index.js
package-lock.json
package.json
spec/DataValueResolver.spec.ts

This PR implements `DataValueResolver`, a helper class for resolving values of any which has been already implemented at `@themost/data@lts`

add data value resolver

---

data-context.js
data-listeners.js
data-model.js

This PR fixes some imports made inside procedures and removes them.

fix require inside procedures

---

OnJsonAttribute.js
data-model.js
data-queryable.js
package-lock.json
package.json
spec/JsonAttribute.spec.ts
spec/test2/config/models/Product.json

This PR updates JSON attributes implementation following changes already applied by `@themost/data@lts`  #189

select and query unknown json attributes

---

OnJsonAttribute.js
data-queryable.js
package-lock.json
package.json
spec/JsonAttribute.spec.ts

This PR merges latest change from `master` into `lts`

merge latest changes from master

---

data-context.js
package-lock.json
package.json
spec/DataAssociationMapping.spec.ts
spec/DataAttributeResolver.spec.ts
spec/DataNestedObjectListener.spec.ts
spec/DataObjectAssociationListener.spec.ts
spec/DataObjectJunction.spec.ts
spec/DataObjectTag.spec.ts
spec/DataValueResolver.spec.ts
spec/FunctionContext.spec.ts
spec/HasParentJunction.spec.ts
spec/OnExecuteNestedQueryable.spec.ts
spec/ParentChildRelationship.spec.ts
spec/ZeroOneMultiplicity.spec.ts

This PR upgrades `DataContext.finalize()` process to follow `DatabaseAdapter.close()` requirements.

upgrade context finalize process

---

data-model.js
package-lock.json
package.json
spec/DataModel.spec.ts
spec/test1/listeners/Employee.beforeUpgrade.ts

This PR enables the registration of before upgrade listeners

use before upgrade listener

---

dataTypes.json
odata.d.ts
odata.js
package-lock.json
package.json
spec/JsonAttribute.spec.ts

This MR follows the intergration of open type json attributes and implements `Edm.Untyped` when presenting service metadata document.
https://docs.oasis-open.org/odata/new-in-odata/v4.01/cn04/new-in-odata-v4.01-cn04.html#sec_NewBuiltinAbstractTypeEdmUntyped

use Edm.Untyped for native json objects

---

dataTypes.json
odata.d.ts
odata.js
package-lock.json
package.json
spec/JsonAttribute.spec.ts

This MR follows update implemented by #215 at `@themost/data@lts`

use Edm.Untyped

---

data-configuration.js
package-lock.json
package.json

This MR update data adapter type loading process and includes a collection of paths relatives to current execution path -the execution directory of an application-

include current execution directory paths when resolving adapter types

---

data-model.js
package-lock.json
package.json

This PR closes #219 and formats index names to support fully qualified database object names like `dbo.UserBase`

format index names while upgrading a data model

---

data-model.js
package-lock.json
package.json
spec/SelectJsonArray.spec.ts

This PR fixes `lodash/isArrayLikeObject` import.

fix lodash/isArrayLikeObject import

---

data-model.js
data-validator.d.ts
data-validator.js
package-lock.json
package.json
spec/DataObjectTag.spec.ts

This PR pushes the changes of #232 that are already committed at LTS version of `@themost/data`

Validate JSON type attributes
